import { parseGraphDocument, prepareGraphExport } from '../src/core';
import type { GraphDocument } from '../src/core';

export interface OfflineShell { titlePrefix: string; prefix: string; suffix: string }
const escapePayload = (value: unknown) => JSON.stringify(value).replace(/</g, '\\u003c').replace(/\u2028/g, '\\u2028').replace(/\u2029/g, '\\u2029');
const escapeTitle = (value: string) => value.replace(/[&<>"']/g, character => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[character]!));

/** The shell is generated by the package's real Node exporter at build time. */
export async function makeOfflineReport(document: GraphDocument, shell: OfflineShell, baseline?: GraphDocument): Promise<string> {
  const projection = prepareGraphExport(document);
  const digest = await crypto.subtle.digest('SHA-256', new TextEncoder().encode(projection.json));
  const documentSha256 = Array.from(new Uint8Array(digest), byte => byte.toString(16).padStart(2, '0')).join('');
  // Never insert raw graph strings into markup, or inherit a graph-supplied assessment.
  const payload = { document: projection.document, ...(baseline ? { baseline: parseGraphDocument(baseline) } : {}), documentSha256 };
  return `${shell.titlePrefix}${escapeTitle(projection.document.title)}${shell.prefix}${escapePayload(payload)}${shell.suffix}`;
}

export function downloadFile(content: string, name: string, type: string): void {
  const url = URL.createObjectURL(new Blob([content], { type }));
  const anchor = window.document.createElement('a');
  anchor.href = url; anchor.download = name;
  window.document.body.append(anchor); anchor.click(); anchor.remove();
  // A later task gives WebKit time to claim the blob for the download.
  window.setTimeout(() => URL.revokeObjectURL(url), 1000);
}

export function fileStem(title: string): string {
  return title.normalize('NFKD').replace(/[^a-zA-Z0-9]+/g, '-').replace(/^-|-$/g, '').slice(0, 90).toLowerCase() || 'orrery-graph';
}
